services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: '98034183'
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - /home/josecicero/Documentos/Estudos/Python/Rocketseat/Project/Flask/sample-flask-auth/mysql:/var/lib/mysql